### ISSUE TITLE
Dropdown not flipping on click, only when scrolling.

### ISSUE THREAD

**Issue by leopowershield** [bootstrap-vue-next/bootstrap-vue-next#1740] opened 2024-01-30 22:54 UTC
### Describe the bug

When there's no space for the dropdown container below the button, it should show on the top. Currently, if the bottom is close to the viewport bottom, it displays the dropdown list with a scroll bar. However, if the user scrolls up and down, the dropdown list will be shown on the top as expected. 

Is there a way to fix it?

### Reproduction

In the DropDown doc page, leave the button Default Alignment next to the bottom, but, completely visible. On click it will render the dropdown list on the bottom instead of on the top.

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment] 2024-02-06 18:51
I would appreciate a better reproduction. An exact position on the dropdown docs page would be useful

**Comment by leopowershield** [comment] 2024-02-06 19:24
Hi, I'm sorry, it is complicated to explain with words. I recorded a video, I hope it helps to explain the undesired behavior.

Here is the link for the video. Please don't hesitate to let me know if you have any issues visualizing it:
[Drop Down flipping behavior](https://jam.dev/c/9e4e9729-7ca5-4d7c-b0c2-2761bdc73388)

**Comment by xvaara** [comment] 2024-02-08 00:04
It seems this happens only on windows (I'll test linux later) and not on mac. For some reason it thinks it can fit the dropdown under the button and adds a scroll to it. Might need to check if floating-ui has had these problems also.

**Comment by VividLemon** [comment] 2024-02-08 00:29
Strange

**Comment by leopowershield** [comment] 2024-02-13 01:12
Hello. Do you know if there's any progress on this item? It is annoying for users and I haven't found any workaround apart from scrolling up and down on button-click events, which creates a weird effect.

**Comment by leopowershield** [comment] 2024-02-13 01:16
Just to let you know, on my application, it is happening even on a Linux / Firefox environment.

**Comment by VividLemon** [comment] 2024-02-13 02:02
> Hello. Do you know if there's any progress on this item? It is annoying for users and I haven't found any workaround apart from scrolling up and down on button-click events, which creates a weird effect.

Feel free to investigate the issue. Sadly I'm not much help here

**Comment by xvaara** [comment] 2024-02-13 10:16
@leopowershield can get around this with no-size prop. The problem was that we were calculating a height for the element before we showed it, and the size was updated on scroll. Will be fixed in the next release.

**Closed by xvaara** 2024-02-13 10:16 UTC
Labels: bug
