### ISSUE TITLE
b-form-file

### ISSUE THREAD

**Issue by loancarre** [bootstrap-vue-next/bootstrap-vue-next#1171] opened 2023-06-07 09:13 UTC
Hello,

i can't find the b-form-file component, did you add it to the project ? 

Thanks

**Comment by VividLemon** [comment] 2023-06-07 15:24
Duplicate of https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/752

**Closed by VividLemon** 2023-06-07 15:24 UTC
Labels: enhancement
