### ISSUE TITLE
Have a autocomplete select

### ISSUE THREAD

**Issue by JLEGit** [bootstrap-vue-next/bootstrap-vue-next#2318] opened 2024-10-31 11:24 UTC
### Clear and concise description of the problem

goal : Be able to search on a select an element

### Suggested solution

Form Select

### Validations

- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by xvaara** [comment] 2024-11-04 12:42
duplicate of #1489

**Closed by xvaara** 2024-11-04 12:42 UTC
Labels: enhancement
