### ISSUE TITLE
bootstrap-vue-next 0.16.x - useToast no longer working in pinia option stores

### ISSUE THREAD

**Issue by xmatthias** [bootstrap-vue-next/bootstrap-vue-next#1747] opened 2024-02-04 06:34 UTC
### Describe the bug

with the update to bootstrap-vue-next 0.16.x, it's no longer possible to trigger toasts from within a pinia store action.

The problematic part is the Action which is supposed to trigger the toast.

The provided reproduction is obviously a **very** simplified example - a real application could be a network call where error handling triggers a toast (that's not really necessary for this reproduction though).

![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/5024695/4b933054-1e69-4faa-abd4-fa73f300c936)

The only way to get it working is by the button "direct toast" - but all useage from within the pinia store seems to be non-working (obviously the toast could be passed into the action as parameter - but i think that's not an approach that should be necessary).

### Reproduction

https://stackblitz.com/~/edit/github-u4mfkf-1hxb9a?file=src%2FuseCounter.ts

### Used Package Manager

n/a

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

---

_There may be workarounds to this by using pinia setup stores - however the [pinia docs](https://pinia.vuejs.org/core-concepts/#What-syntax-should-I-pick-) themselfs suggest to start with options stores - aside from the fact that it's beyond the point which type of pinia store a user of a library prefers._

**Comment by VividLemon** [comment] 2024-02-04 20:04
Thank you for your continued interest and contributions to our library. I am truly appreciative of your efforts. However, as previously discussed, the behavior you're experiencing is not a bug within this library

Here are the references that explain why:

Reference 1: [Pinia Composables](https://pinia.vuejs.org/cookbook/composables.html)
![Screenshot from 2024-02-04 13-33-40](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/31498096/135ac071-98dd-4f7a-bf4f-234cadade2ed)

Reference 2: [Pinia Core Concepts](https://pinia.vuejs.org/core-concepts/#Setup-Stores)
![Screenshot from 2024-02-04 13-45-32](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/31498096/be905e83-0424-43f6-b975-8f5fbca2e928)

Reference 3: [Vue.js Composables Usage Restrictions](https://vuejs.org/guide/reusability/composables#usage-restrictions)
![Screenshot from 2024-02-04 13-47-38](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/31498096/f84a0109-494c-4f18-95dd-01dc58746b3c)

These references were also provided in our previous discussion on Discord. 

I understand that the changes in 0.16 may have caused some disruptions in your codebase. Dealing with breaking changes can indeed be challenging. However, this could be a valuable opportunity to deepen your understanding of both Pinia and Vuejs

I would encourage you to reach out to the Pinia or Vue.js communities for further assistance. They have a wealth of knowledge and experience that could be beneficial in resolving your issue

Thank you for your understanding and cooperation

**Closed by VividLemon** 2024-02-04 20:04 UTC
Labels: bug

**Comment by xmatthias** [comment] 2024-02-05 05:38
![image](https://github.com/bootstrap-vue-next/bootstrap-vue-next/assets/5024695/54044b22-8d81-4a14-896b-62c47a43fd3d)

@VividLemon 
Well you can cross out the relevant sections - but it won't change the fact that it's written there.
pinia itself recomments "try the options store first" - which makes it **the recommendation** in the view of most people reading this section.

Can you maybe also point me to where in the bootstrap-vue-next documentation you're pointing out that use of this library **FORCES** the use of a specific type of pinia store?
(if not there, i'd strongly recommend to add it as a warning to ANY setting and composable where it's still missing and applies)

> I would encourage you to reach out to the Pinia or Vue.js communities for further assistance. They have a wealth of knowledge and experience that could be beneficial in resolving your issue

I do know HOW to resolve the issue **by not using the composable** (that's not the point - i do WANT to use the methods a library provides) - but it involves workarounds which i'd hope i don't have to apply if i use a library like bootstrap-vue.

I'd encourage yourself to reach out to these communities, too - to get a feel on how well liked (or rather not) setup stores are - as so far, i'm rarely comming across people actively using setup stores unles they're forced to for one reason or another (having to return your state simply feels like a step back).

---

bootstrap-vue-next just made a terrible usability mistake in my eyes, one i hope you'll be able to correct once you're able to step over your ego ("i wrote this code and it's beautiful") and actualy have a look at what **the user need is**.

**Comment by VividLemon** [comment] 2024-02-05 17:16
I'm not reading anything here. The simple fact is you ignored all if the libraries you were using and decided to do your own thing. Its not bvns issue that you were always using composables wrong. You have nobody to blame but yourself. 

Don't make another issue. Consider this a formal warning https://github.com/bootstrap-vue-next/bootstrap-vue-next?tab=coc-ov-file#2-warning
