### ISSUE TITLE
After 0.15.0 btable sorting bug

### ISSUE THREAD

**Issue by raizdev** [bootstrap-vue-next/bootstrap-vue-next#1608] opened 2023-11-19 09:40 UTC
### Describe the bug

After 0.15.0 sorting is not going well.

1
2
3
11
12
13

becomes

1
11
12
13
2
3
4

### Reproduction

-

### Used Package Manager

pnpm

### Validations

- [X] Have tested with the latest version. This is still alpha version and sometime things change rapidly.
- [X] Follow our [Code of Conduct](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/bootstrap-vue-next/bootstrap-vue-next/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by corymccarty** [comment] 2023-12-07 22:01
Reproduction [here](https://stackblitz.com/edit/github-dhdyvn?file=src%2FApp.vue). It looks like the issue is that the built-in sorting is forcing everything into a string representation and then sorting based on the string, so multi-digit numbers are ordered based on the most significant digit.

**Comment by dwgray** [comment] 2024-03-01 01:59
This was fixed by v16.6 (at least) - [here's](https://stackblitz.com/edit/github-dhdyvn-997dng) the reproduction updated to that version.  I'm not seeing the exact PR that fixed it but I know that it was working by the time I submitted #1771.

**Comment by VividLemon** [comment] 2024-03-01 17:40
Fixed by https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1772

**Closed by VividLemon** 2024-03-01 17:40 UTC
Labels: bug
