### ISSUE TITLE
Variant props like `body-bg-variant`, `footer-bg-variant`, `border-variant` should also support strings for custom theme colors

### ISSUE THREAD

**Issue by sceee** [bootstrap-vue-next/bootstrap-vue-next#1169] opened 2023-06-06 16:15 UTC
**Is your feature request related to a problem? Please describe.**

Bootstrap allows to [extend the base color map](https://getbootstrap.com/docs/5.3/utilities/colors/#sass-utilities-api). To be able to use these with several components in a typescript project, the variant class props should also support arbitrary strings as value.

**Describe the solution you would like.**

The following code works (e.g. for a `b-card` component):
```
<b-card
body-bg-variant="white">
...
</b-card>
```
(Currently it emits the following TS error: `Type '"white"' is not assignable to type 'keyof BaseColorVariant | null | undefined'`)

The solution would be that the type definition for the property is:
```
bodyBgVariant: keyof import("../../types").BaseColorVariant | string | null | undefined;
```
(string is added)

This also applies to other similar properties.

**Describe alternatives you have considered.**
Using css variables / style overrides.

_Hack:_ Ignore type check by doing something like
`:body-bg-variant="'white' as unknown as keyof BaseColorVariant"`

**Additional context.**

**Comment by VividLemon** [comment] 2023-06-06 16:17
Duplicate of https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/1093

**Closed by VividLemon** 2023-06-06 16:17 UTC
Labels: enhancement
