### ISSUE TITLE
The building process for PRs seem to be broken

### ISSUE THREAD

**Issue by anrolmar** [bootstrap-vue-next/bootstrap-vue-next#1711] opened 2024-01-07 18:57 UTC
When we try to do a new PR, the building process seem to be broken because it fails 360 mins after starting it.

I had this "bug" for these PRs:

https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1707
https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1705
https://github.com/bootstrap-vue-next/bootstrap-vue-next/pull/1696

**Comment by VividLemon** [comment] 2024-01-07 19:23
Duplicate of https://github.com/bootstrap-vue-next/bootstrap-vue-next/issues/1702

**Closed by VividLemon** 2024-01-07 19:23 UTC
Labels: question
